In [5]:
import torch
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [6]:
query = inputs[1]                            #1
attn_scores_2 = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(x_i, query)
print(attn_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [7]:
res = 0.
for idx, element in enumerate(inputs[0]):
    res += inputs[0][idx] * query[idx]
print(res)
print(torch.dot(inputs[0], query))

tensor(0.9544)
tensor(0.9544)


In [8]:
attn_weights_2_tmp = attn_scores_2 / attn_scores_2.sum()
print("Attention scores:", attn_scores_2)
print("Attention weights:", attn_weights_2_tmp)
print("Sum:", attn_weights_2_tmp.sum())

Attention scores: tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])
Attention weights: tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])
Sum: tensor(1.0000)


In [9]:
def softmax_naive(x):
    return torch.exp(x) / torch.exp(x).sum(dim=0)

attn_weights_2_naive = softmax_naive(attn_scores_2)
print("Attention weights:", attn_weights_2_naive)
print("Sum:", attn_weights_2_naive.sum())

Attention weights: tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Sum: tensor(1.)


In [10]:
sm_func = torch.nn.Softmax(dim=0)
attn_weights_2_tsm = sm_func(attn_scores_2)
print("Attention weights:", attn_weights_2_tsm)
print("Sum:", attn_weights_2_tsm.sum())

Attention weights: tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Sum: tensor(1.)


In [11]:
attn_weights_2 = torch.softmax(attn_scores_2, dim=0)
print("Attention weights:", attn_weights_2)
print("Sum:", attn_weights_2.sum())

Attention weights: tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Sum: tensor(1.)


In [12]:
inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])

In [13]:
query = inputs[1]         #1
context_vec_2 = torch.zeros(query.shape)
for i,x_i in enumerate(inputs):
    context_vec_2 += attn_weights_2[i]*x_i
print(context_vec_2)

tensor([0.4419, 0.6515, 0.5683])


In [14]:
attn_weights_2 @ inputs

tensor([0.4419, 0.6515, 0.5683])

In [15]:
context_vec_2 = torch.zeros(query.shape)
for i in range(inputs.shape[0]):
    context_vec_2 += attn_weights_2[i]*inputs[i]
print(context_vec_2)

tensor([0.4419, 0.6515, 0.5683])


In [16]:
inputs.shape

torch.Size([6, 3])

In [17]:
attn_scores = torch.empty(inputs.shape[0], inputs.shape[0])
for i, x_i in enumerate(inputs):
    for j, x_j in enumerate(inputs):
        attn_scores[i, j] = torch.dot(x_i, x_j)
print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [18]:
attn_scores = inputs @ inputs.T
print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [19]:
attn_weights = torch.softmax(attn_scores, dim=-1)
print(attn_weights)

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


In [20]:
row_2_sum = attn_weights[1].sum()
print("Row 2 sum:", row_2_sum)
print("All row sums:", attn_weights.sum(dim=-1))

Row 2 sum: tensor(1.)
All row sums: tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [21]:
all_context_vecs = attn_weights @ inputs
print(all_context_vecs)

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])


In [22]:
print("Previous 2nd context vector:", context_vec_2)

Previous 2nd context vector: tensor([0.4419, 0.6515, 0.5683])


In [23]:
x_2 = inputs[1]     #1
d_in = inputs.shape[1]      #2
d_out = d_in

In [24]:
W_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_key   = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)

In [25]:
query_2 = x_2 @ W_query 
key_2 = x_2 @ W_key 
value_2 = x_2 @ W_value
print(query_2)

tensor([0.9570, 1.7375, 0.6252])


In [26]:
keys = inputs @ W_key 
values = inputs @ W_value
print("keys.shape:", keys.shape)
print("values.shape:", values.shape)

keys.shape: torch.Size([6, 3])
values.shape: torch.Size([6, 3])


In [27]:
keys_2 = keys[1]             #1
attn_score_22 = query_2.dot(keys_2)
print(attn_score_22)

tensor(4.5048)


In [28]:
attn_scores_2 = query_2 @ keys.T       #1
print(attn_scores_2)

tensor([3.8246, 4.5048, 4.4410, 2.4036, 2.0424, 3.1900])


In [29]:
keys.shape[-1]

3

In [30]:
d_k = keys.shape[-1]
attn_weights_2 = torch.softmax(attn_scores_2 / d_k**0.5, dim=-1)
print(attn_weights_2)
print(attn_weights_2.sum())

tensor([0.1852, 0.2743, 0.2644, 0.0815, 0.0662, 0.1284])
tensor(1.)


In [31]:
context_vec_2 = attn_weights_2 @ values
print(context_vec_2)

tensor([1.0258, 0.8922, 0.9975])


# Q, K, V

In [32]:
import torch.nn as nn
class SelfAttention_v1(nn.Module):
    def __init__(self, d_in, d_out):
        super().__init__()
        self.W_query = nn.Parameter(torch.rand(d_in, d_out))
        self.W_key   = nn.Parameter(torch.rand(d_in, d_out))
        self.W_value = nn.Parameter(torch.rand(d_in, d_out))

    def forward(self, x):
        keys = x @ self.W_key
        queries = x @ self.W_query
        values = x @ self.W_value
        attn_scores = queries @ keys.T # omega
        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5, dim=-1
        )
        context_vec = attn_weights @ values
        return context_vec

In [33]:
d_in, d_out

(3, 3)

In [36]:
sa_v1 = SelfAttention_v1(d_in, d_out)
print(sa_v1(inputs))

tensor([[1.1916, 1.0666, 1.0965],
        [1.2295, 1.1008, 1.1298],
        [1.2283, 1.0997, 1.1288],
        [1.1739, 1.0505, 1.0804],
        [1.1696, 1.0465, 1.0765],
        [1.1921, 1.0670, 1.0967]], grad_fn=<MmBackward0>)


In [37]:
class SelfAttention_v2(nn.Module):
    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

    def forward(self, x):
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5, dim=-1
        )
        context_vec = attn_weights @ values
        return context_vec

In [38]:
sa_v2 = SelfAttention_v2(d_in, d_out)
print(sa_v2(inputs))

tensor([[-0.3212, -0.1542,  0.3613],
        [-0.3278, -0.1525,  0.3668],
        [-0.3277, -0.1524,  0.3667],
        [-0.3255, -0.1536,  0.3666],
        [-0.3250, -0.1506,  0.3637],
        [-0.3262, -0.1548,  0.3678]], grad_fn=<MmBackward0>)


In [39]:
queries = sa_v2.W_query(inputs)     #1
keys = sa_v2.W_key(inputs) 
attn_scores = queries @ keys.T
attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)
print(attn_weights)

tensor([[0.1688, 0.1651, 0.1655, 0.1653, 0.1735, 0.1616],
        [0.1581, 0.1769, 0.1770, 0.1596, 0.1687, 0.1597],
        [0.1580, 0.1766, 0.1768, 0.1599, 0.1689, 0.1599],
        [0.1614, 0.1742, 0.1742, 0.1615, 0.1662, 0.1625],
        [0.1575, 0.1683, 0.1686, 0.1678, 0.1723, 0.1655],
        [0.1627, 0.1774, 0.1773, 0.1581, 0.1643, 0.1602]],
       grad_fn=<SoftmaxBackward0>)


In [44]:
context_length = attn_scores.shape[0]
mask_simple = torch.tril(torch.ones(context_length, context_length))
print(mask_simple)
masked_simple = attn_weights*mask_simple
print(masked_simple)

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])
tensor([[0.1688, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1581, 0.1769, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1580, 0.1766, 0.1768, 0.0000, 0.0000, 0.0000],
        [0.1614, 0.1742, 0.1742, 0.1615, 0.0000, 0.0000],
        [0.1575, 0.1683, 0.1686, 0.1678, 0.1723, 0.0000],
        [0.1627, 0.1774, 0.1773, 0.1581, 0.1643, 0.1602]],
       grad_fn=<MulBackward0>)


In [43]:
masked_simple = torch.tril(attn_weights)
print(masked_simple)

tensor([[0.1688, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1581, 0.1769, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1580, 0.1766, 0.1768, 0.0000, 0.0000, 0.0000],
        [0.1614, 0.1742, 0.1742, 0.1615, 0.0000, 0.0000],
        [0.1575, 0.1683, 0.1686, 0.1678, 0.1723, 0.0000],
        [0.1627, 0.1774, 0.1773, 0.1581, 0.1643, 0.1602]],
       grad_fn=<TrilBackward0>)


In [45]:
row_sums = masked_simple.sum(dim=-1, keepdim=True)
masked_simple_norm = masked_simple / row_sums
print(masked_simple_norm)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4720, 0.5280, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3089, 0.3454, 0.3457, 0.0000, 0.0000, 0.0000],
        [0.2404, 0.2595, 0.2595, 0.2406, 0.0000, 0.0000],
        [0.1887, 0.2017, 0.2020, 0.2011, 0.2064, 0.0000],
        [0.1627, 0.1774, 0.1773, 0.1581, 0.1643, 0.1602]],
       grad_fn=<DivBackward0>)


In [46]:
mask = torch.triu(torch.ones(context_length, context_length), diagonal=1)
masked = attn_scores.masked_fill(mask.bool(), -torch.inf)
print(masked)

tensor([[ 0.0013,    -inf,    -inf,    -inf,    -inf,    -inf],
        [ 0.1921,  0.3865,    -inf,    -inf,    -inf,    -inf],
        [ 0.1802,  0.3733,  0.3748,    -inf,    -inf,    -inf],
        [ 0.1544,  0.2865,  0.2865,  0.1554,    -inf,    -inf],
        [-0.0846,  0.0306,  0.0332,  0.0253,  0.0705,    -inf],
        [ 0.2740,  0.4243,  0.4236,  0.2251,  0.2910,  0.2480]],
       grad_fn=<MaskedFillBackward0>)


In [47]:
attn_weights = torch.softmax(masked / keys.shape[-1]**0.5, dim=1)
print(attn_weights)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4720, 0.5280, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3089, 0.3454, 0.3457, 0.0000, 0.0000, 0.0000],
        [0.2404, 0.2595, 0.2595, 0.2406, 0.0000, 0.0000],
        [0.1887, 0.2017, 0.2020, 0.2011, 0.2064, 0.0000],
        [0.1627, 0.1774, 0.1773, 0.1581, 0.1643, 0.1602]],
       grad_fn=<SoftmaxBackward0>)


In [48]:
dropout = torch.nn.Dropout(0.5)    #1
example = torch.ones(6, 6)      #2
print(dropout(example))

tensor([[2., 2., 2., 2., 2., 2.],
        [2., 2., 0., 2., 0., 2.],
        [0., 0., 0., 2., 0., 0.],
        [2., 2., 0., 2., 0., 0.],
        [0., 2., 2., 0., 2., 0.],
        [2., 2., 2., 2., 2., 2.]])


In [52]:
print(dropout(attn_weights))

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.9439, 1.0561, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.6179, 0.6908, 0.6914, 0.0000, 0.0000, 0.0000],
        [0.4809, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3775, 0.0000, 0.4040, 0.0000, 0.0000, 0.0000],
        [0.3253, 0.3548, 0.3546, 0.0000, 0.3285, 0.3205]],
       grad_fn=<MulBackward0>)


In [53]:
batch = torch.stack((inputs, inputs), dim=0)
print(batch.shape)     

torch.Size([2, 6, 3])


In [54]:
inputs.shape

torch.Size([6, 3])

In [55]:
class CausalAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length,
                dropout: float = 0.5, qkv_bias=False):
        super().__init__()
        self.d_out = d_out
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.dropout = nn.Dropout(dropout)            #1
        self.register_buffer(
           'mask',
           torch.triu(torch.ones(context_length, context_length),
           diagonal=1)
        )             #2

    def forward(self, x):
        b, num_tokens, d_in = x.shape                   #3
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)

        attn_scores = queries @ keys.transpose(1, 2)   
        attn_scores.masked_fill_(                    #4
            self.mask.bool()[:num_tokens, :num_tokens], -torch.inf
        ) 
        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5, dim=-1
        )
        attn_weights = self.dropout(attn_weights)

        context_vec = attn_weights @ values
        return context_vec

In [57]:
context_length

6

In [56]:
torch.manual_seed(123)
context_length = batch.shape[1]
ca = CausalAttention(d_in, d_out, context_length, 0.0)
context_vecs = ca(batch)
print("context_vecs.shape:", context_vecs.shape)

context_vecs.shape: torch.Size([2, 6, 3])


In [59]:
class MultiHeadAttentionWrapper(nn.Module):
    def __init__(self, d_in, d_out, context_length,
                 dropout: float = 0.5, num_heads = 2, qkv_bias=False):
        super().__init__()
        self.heads = nn.ModuleList(
            [CausalAttention(
                 d_in, d_out, context_length, dropout, qkv_bias
             ) 
             for _ in range(num_heads)]
        )

    def forward(self, x):
        return torch.cat([head(x) for head in self.heads], dim=-1)

In [60]:
batch.shape[1]

6

In [61]:
context_length

6

In [62]:
context_length = batch.shape[1] # This is the number of tokens
d_in, d_out = 3, 3
mha = MultiHeadAttentionWrapper(
    d_in, d_out, context_length, 0.0, num_heads=4
)
context_vecs = mha(batch)

print(context_vecs)
print("context_vecs.shape:", context_vecs.shape)

tensor([[[ 0.0752,  0.4566,  0.2729, -0.0322, -0.4610,  0.2847, -0.3886,
          -0.1471,  0.4106,  0.2869,  0.2964, -0.1885],
         [ 0.0313,  0.5977,  0.3053, -0.2642, -0.3017,  0.4047, -0.1700,
          -0.2532,  0.3527,  0.3626,  0.2247, -0.3241],
         [ 0.0178,  0.6413,  0.3138, -0.3371, -0.2502,  0.4369, -0.1055,
          -0.2813,  0.3304,  0.3880,  0.2032, -0.3675],
         [ 0.0089,  0.5729,  0.2785, -0.3210, -0.2028,  0.4068, -0.0654,
          -0.2649,  0.2920,  0.3533,  0.1571, -0.3522],
         [ 0.0071,  0.5566,  0.2514, -0.3377, -0.1566,  0.3424, -0.0584,
          -0.2268,  0.2288,  0.3361,  0.1866, -0.3058],
         [ 0.0023,  0.5363,  0.2508, -0.3262, -0.1548,  0.3678, -0.0315,
          -0.2445,  0.2433,  0.3284,  0.1422, -0.3274]],

        [[ 0.0752,  0.4566,  0.2729, -0.0322, -0.4610,  0.2847, -0.3886,
          -0.1471,  0.4106,  0.2869,  0.2964, -0.1885],
         [ 0.0313,  0.5977,  0.3053, -0.2642, -0.3017,  0.4047, -0.1700,
          -0.2532,  0.

In [63]:
class MultiHeadAttention(nn.Module):
    def __init__(self, d_in, d_out, 
                 context_length, dropout, num_heads, qkv_bias=False):
        super().__init__()
        assert (d_out % num_heads == 0), \
            "d_out must be divisible by num_heads"

        self.d_out = d_out
        self.num_heads = num_heads
        self.head_dim = d_out // num_heads    #1
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.out_proj = nn.Linear(d_out, d_out)    #2
        self.dropout = nn.Dropout(dropout)
        self.register_buffer(
            "mask",
            torch.triu(torch.ones(context_length, context_length),
                       diagonal=1)
        )

    def forward(self, x):
        b, num_tokens, d_in = x.shape
        keys = self.W_key(x)         #3
        queries = self.W_query(x)    #3
        values = self.W_value(x)     #3

        keys = keys.view(b, num_tokens, self.num_heads, self.head_dim)       #4
        values = values.view(b, num_tokens, self.num_heads, self.head_dim)  
        queries = queries.view(                                             
            b, num_tokens, self.num_heads, self.head_dim                    
        )                                                                   

        keys = keys.transpose(1, 2)          #5
        queries = queries.transpose(1, 2)    #5
        values = values.transpose(1, 2)      #5

        attn_scores = queries @ keys.transpose(2, 3)   #6
        mask_bool = self.mask.bool()[:num_tokens, :num_tokens]    #7

        attn_scores.masked_fill_(mask_bool, -torch.inf)     #8

        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5, dim=-1)
        attn_weights = self.dropout(attn_weights)

        context_vec = (attn_weights @ values).transpose(1, 2)   #9
 #10
        context_vec = context_vec.contiguous().view(
            b, num_tokens, self.d_out
        )
        context_vec = self.out_proj(context_vec)    #11
        return context_vec

In [64]:
a = torch.tensor([[[[0.2745, 0.6584, 0.2775, 0.8573],    #1
                    [0.8993, 0.0390, 0.9268, 0.7388],
                    [0.7179, 0.7058, 0.9156, 0.4340]],

                   [[0.0772, 0.3565, 0.1479, 0.5331],
                    [0.4066, 0.2318, 0.4545, 0.9737],
                    [0.4606, 0.5159, 0.4220, 0.5786]]]])

In [65]:
a.shape

torch.Size([1, 2, 3, 4])

In [67]:
b = a @ a.transpose(2, 3)

In [68]:
b.shape

torch.Size([1, 2, 3, 3])

In [69]:
torch.manual_seed(123)
batch_size, context_length, d_in = batch.shape
d_out = 2
mha = MultiHeadAttention(d_in, d_out, context_length, 0.0, num_heads=2)
context_vecs = mha(batch)
print(context_vecs)
print("context_vecs.shape:", context_vecs.shape)

tensor([[[0.3190, 0.4858],
         [0.2943, 0.3897],
         [0.2856, 0.3593],
         [0.2693, 0.3873],
         [0.2639, 0.3928],
         [0.2575, 0.4028]],

        [[0.3190, 0.4858],
         [0.2943, 0.3897],
         [0.2856, 0.3593],
         [0.2693, 0.3873],
         [0.2639, 0.3928],
         [0.2575, 0.4028]]], grad_fn=<ViewBackward0>)
context_vecs.shape: torch.Size([2, 6, 2])
