In [1]:
import urllib.request
url = ("https://raw.githubusercontent.com/rasbt/"
       "LLMs-from-scratch/main/ch02/01_main-chapter-code/"
       "the-verdict.txt")
file_path = "the-verdict.txt"
urllib.request.urlretrieve(url, file_path)

('the-verdict.txt', <http.client.HTTPMessage at 0x29e42fb6810>)

In [2]:
!du -sh the-verdict.txt
!du -sh The_Mathematical_Principles_of_Natural_Philosophy_1729.txt

20K	the-verdict.txt
1.3M	The_Mathematical_Principles_of_Natural_Philosophy_1729.txt


In [3]:
book_txt = 'The_Mathematical_Principles_of_Natural_Philosophy_1729.txt'
with open(book_txt, "r", encoding="utf-8") as f:
    raw_text = f.read()
print("Total number of character:", len(raw_text))
print(raw_text[:120].replace('\n',''))

Total number of character: 1267243
The Mathematical Principles of Natural Philosophy (1729)					Isaac Newton1729Exported from Wikisource on 


In [4]:
book_txt_2 = 'the-verdict.txt'
with open(book_txt_2, "r", encoding="utf-8") as f:
    raw_text += '\n\n\n\n' + f.read()
print("Total number of character:", len(raw_text))
print(raw_text[:120].replace('\n',''))

Total number of character: 1287726
The Mathematical Principles of Natural Philosophy (1729)					Isaac Newton1729Exported from Wikisource on 


In [5]:
import re
text = "Hello, world. This, is a test."
result = re.split(r'(\s)', text)
print(result)

['Hello,', ' ', 'world.', ' ', 'This,', ' ', 'is', ' ', 'a', ' ', 'test.']


In [6]:
result = re.split(r'([,.]|\s)', text)
print(result)

['Hello', ',', '', ' ', 'world', '.', '', ' ', 'This', ',', '', ' ', 'is', ' ', 'a', ' ', 'test', '.', '']


In [7]:
result = [item for item in result if item.strip()]
print(result)

['Hello', ',', 'world', '.', 'This', ',', 'is', 'a', 'test', '.']


In [8]:
text = "Hello, world. Is this-- a test?"
result = re.split(r'([,.:;?_!"()\']|--|\s)', text)
result = [item.strip() for item in result if item.strip()]
print(result)

['Hello', ',', 'world', '.', 'Is', 'this', '--', 'a', 'test', '?']


In [9]:
from string import punctuation
punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [10]:
r"\""

'\\"'

In [11]:
ponc_re_pattern = r'([!"#$%&\'()*+,-./:;<=>?@\[\\\]\^_`{|}~]|--|\s)'

In [12]:
result = re.split(ponc_re_pattern, text)
result

['Hello',
 ',',
 '',
 ' ',
 'world',
 '.',
 '',
 ' ',
 'Is',
 ' ',
 'this',
 '-',
 '',
 '-',
 '',
 ' ',
 'a',
 ' ',
 'test',
 '?',
 '']

In [13]:
preprocessed = re.split(r'(\'s|[,.:;?_!"()\']|--|\s)', raw_text)
preprocessed = [item.strip() for item in preprocessed if item.strip()]
print(len(preprocessed))
print(preprocessed[:30])
all_words = sorted(set(preprocessed))
vocab_size = len(all_words)
print(vocab_size)

276215
['The', 'Mathematical', 'Principles', 'of', 'Natural', 'Philosophy', '(', '1729', ')', 'Isaac', 'Newton', '1729', 'Exported', 'from', 'Wikisource', 'on', 'March', '3', ',', '2025', 'This', 'work', 'is', 'incomplete', '.', 'If', 'you', "'", 'd', 'like']
8476


In [14]:
'\'s' in all_words

True

In [15]:
all_words.index('\'s')

7

In [16]:
all_words[7]

"'s"

In [17]:
preprocessed_plus = re.split(ponc_re_pattern, raw_text)
preprocessed_plus = [item.strip() for item in preprocessed_plus if item.strip()]
print(len(preprocessed_plus))
print(preprocessed_plus[:30])
all_words_plus = sorted(set(preprocessed_plus))
vocab_size = len(all_words_plus)
print(vocab_size)

278791
['The', 'Mathematical', 'Principles', 'of', 'Natural', 'Philosophy', '(', '1729', ')', 'Isaac', 'Newton', '1729', 'Exported', 'from', 'Wikisource', 'on', 'March', '3', ',', '2025', 'This', 'work', 'is', 'incomplete', '.', 'If', 'you', "'", 'd', 'like']
8173


In [18]:
set(preprocessed_plus) ^ set(preprocessed)

{'#',
 '#12',
 '%',
 '%PS*',
 '&c',
 "'s",
 '+/-',
 '+2',
 '+a',
 '--',
 '-1-r',
 '-2A',
 '-2aA-3',
 '-4-',
 '-4-¢',
 '-44-am',
 '-7',
 '-According',
 '-B',
 '-FF',
 '-I2',
 '-a',
 '-a/A²',
 '-a/e',
 '-aA-2',
 '-aa',
 '-and',
 '-as',
 '-gd',
 '-na/An+1',
 '-o',
 '-two',
 '-xx',
 '-½aA-3/2',
 '/-aa-|-zdxtis',
 '/-¢¢',
 '/-“',
 '/1',
 '/1€2',
 '/E',
 '/N',
 '/T',
 '/b',
 '/m',
 '/ms',
 '/n',
 '0—1',
 '1-',
 '1-½n',
 '1/10',
 '1/1067',
 '1/16',
 '1/169282',
 '1/2',
 '1/2000',
 '1/242',
 '1/2aA-3/2',
 '1/3',
 '1/3021',
 '1/3342',
 '1/3761/50',
 '1/3aA-2/3',
 '1/4',
 '1/656',
 '1/69',
 '1/78',
 '1/8',
 '1/A',
 '1/An',
 '1/GD',
 '1/SP',
 '1/√SP',
 '101',
 '101/2',
 '1067',
 '107/10',
 '10BV3',
 '11/2',
 '11/5',
 '111/3',
 '1113',
 '1113/16',
 '1195',
 '1195/29',
 '11AV',
 '11Aa',
 '11V',
 '121/12',
 '122',
 '122/3',
 '1242',
 '1242/31',
 '1243',
 '1243/31',
 '13/4',
 '131',
 '131/3',
 '132/3',
 '13219',
 '13219/40',
 '1343',
 '1343/8',
 '136/11',
 '136/11V',
 '1392',
 '1392/5',
 '145',
 '145

In [19]:
set(all_words_plus) - set(all_words)

{'#',
 '%',
 '0—1',
 '101',
 '1067',
 '10BV3',
 '1113',
 '1195',
 '11AV',
 '11Aa',
 '11V',
 '122',
 '1242',
 '1243',
 '131',
 '13219',
 '1343',
 '1392',
 '145',
 '1541',
 '155',
 '15613',
 '15h',
 '1621',
 '1661',
 '167',
 '169282',
 '1831',
 '187',
 '1903',
 '191',
 '1931',
 '1Am',
 '1Bn',
 '1€2',
 '2000',
 '211',
 '212',
 '2121',
 '221',
 '222',
 '242',
 '2531',
 '261',
 '2933',
 '2A1',
 '2Ba',
 '2NI',
 '2P',
 '2aA1',
 '2bA³B',
 '2e',
 '2e5',
 '2e³',
 '2t',
 '2tt',
 '3021',
 '329',
 '3342',
 '351',
 '3519',
 '35½',
 '3761',
 '391',
 '3AS',
 '3Ba',
 '3D',
 '3aA',
 '3aA²B',
 '3b',
 '412',
 '442',
 '443',
 '444',
 '445',
 '446',
 '447',
 '448',
 '449',
 '450',
 '451',
 '452',
 '454',
 '457',
 '458',
 '459',
 '460',
 '471',
 '4715',
 '478',
 '479',
 '480',
 '481',
 '482',
 '484',
 '485',
 '486',
 '487',
 '488',
 '489',
 '490',
 '491',
 '492',
 '493',
 '495',
 '496',
 '497',
 '499',
 '4Aa',
 '4c',
 '500',
 '501',
 '502',
 '5023',
 '503',
 '504',
 '505',
 '506',
 '507',
 '508',
 '509',
 '5

In [20]:
#preprocessed = preprocessed_plus

In [21]:
all_words = sorted(set(preprocessed))
vocab_size = len(all_words)
print(vocab_size)

8476


In [22]:
from collections import Counter

In [23]:
vocab_counts = Counter(preprocessed).most_common()
len(vocab_counts)

8476

In [24]:
vocab_counts[:10]

[('the', 27165),
 (',', 17252),
 ('.', 12074),
 ('of', 10557),
 ('and', 7596),
 ('to', 6974),
 ('in', 5864),
 ('is', 4010),
 ('be', 4001),
 ('as', 3341)]

In [25]:
# I'll not use this approach
# vocab = {token:integer for integer,token in enumerate(all_words)}

class SimpleTokenizerV1:
    def __init__(self, vocab_or_processed, order_by_most_common = True):
        self.str_proc_re_pattern = r'(\'s|[,.:;?_!"()\']|--|\s)'
        if order_by_most_common:
            vocab_counts = Counter(vocab_or_processed).most_common()
            vocab_or_processed = {token:1+integer for integer,(token, _) in enumerate(vocab_counts)}
        self.str_to_int = vocab_or_processed
        self.int_to_str = {i:s for s,i in vocab_or_processed.items()}

    def encode(self, text):         #3
        preprocessed = re.split(self.str_proc_re_pattern, text)
        preprocessed = [
            item.strip() for item in preprocessed if item.strip()
        ]
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids

    def decode(self, ids):         #4
        text = " ".join([self.int_to_str[i] for i in ids]) 

        text = re.sub(self.str_proc_re_pattern, r'\1', text)    #5
        return text

In [26]:
tokenizer = SimpleTokenizerV1(preprocessed)
text = """"It's the last he painted, you know," 
       Mrs. Gisburn said with pardonable pride."""
ids = tokenizer.encode(text)
print(ids)

[140, 426, 124, 1, 257, 319, 2424, 2, 513, 773, 2, 140, 1041, 3, 1127, 494, 22, 8260, 5216, 3]


In [27]:
print(tokenizer.decode(ids[0:4]))

" It 's the


In [28]:
text = "Hello, do you like tea?"
print(tokenizer.encode(text))

KeyError: 'Hello'

In [ ]:
all_tokens = sorted(list(set(preprocessed)))
all_tokens.extend(["<|endoftext|>", "<|unk|>"])
vocab = {token:integer for integer,token in enumerate(all_tokens)}

print(len(vocab.items()))

In [29]:
class SimpleTokenizerV2:
    def __init__(self, vocab_or_processed, order_by_most_common = True):
        reserved_tokens = ["<|endoftext|>", "<|unk|>"]
        self.unk = reserved_tokens[1]
        self.eot = reserved_tokens[0]
        shift_iteger = len(reserved_tokens)
        self.str_to_int = {token: i+1 for i, token in enumerate(reserved_tokens)}
        self.str_proc_re_pattern = r'(\'s|[,.:;?_!"()\']|--|\s)'
        if order_by_most_common:
            vocab_counts = Counter(vocab_or_processed).most_common()
            vocab_or_processed = {token:1+integer+shift_iteger for integer,(token, _) in enumerate(vocab_counts)}
        self.str_to_int.update(vocab_or_processed)
        self.int_to_str = {i:s for s,i in self.str_to_int.items()}

    def encode(self, text):
        preprocessed = re.split(self.str_proc_re_pattern, text)
        preprocessed = [
            item.strip() for item in preprocessed if item.strip()
        ]
        preprocessed = [item if item in self.str_to_int            #1
                        else self.unk for item in preprocessed]
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids

    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        text = re.sub(self.str_proc_re_pattern, r'\1', text)   #2
        return text

In [30]:
tokenizer = SimpleTokenizerV2(preprocessed)
text = """"It's the last he painted, you know," 
       Mrs. Gisburn said with pardonable pride."""
ids = tokenizer.encode(text)
print(ids)

[142, 428, 126, 3, 259, 321, 2426, 4, 515, 775, 4, 142, 1043, 5, 1129, 496, 24, 8262, 5218, 5]


In [31]:
print(tokenizer.decode(ids))

" It 's the last he painted , you know , " Mrs . Gisburn said with pardonable pride .


In [32]:
text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."
text = " <|endoftext|> ".join((text1, text2))
print(text)

Hello, do you like tea? <|endoftext|> In the sunlit terraces of the palace.


In [33]:
print(tokenizer.encode(text))

[2, 4, 353, 515, 181, 8088, 649, 1, 221, 3, 8154, 8084, 6, 3, 2, 5]


In [34]:
print(tokenizer.decode(tokenizer.encode(text)))

<|unk|> , do you like tea ? <|endoftext|> In the sunlit terraces of the <|unk|> .


In [35]:
from importlib.metadata import version
import tiktoken
print("tiktoken version:", version("tiktoken"))

tiktoken version: 0.9.0


In [36]:
tokenizer = tiktoken.get_encoding("gpt2")

In [37]:
text = (
    "Hello, do you like tea? <|endoftext|> In the sunlit terraces"
     "of someunknownPlace."
)
integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})
print(integers)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 1659, 617, 34680, 27271, 13]


In [38]:
enc_text = tokenizer.encode(raw_text)
print(len(enc_text))

310267


In [39]:
enc_sample = enc_text[50:]
#enc_sample

In [40]:
context_size = 4         #1
x = enc_sample[:context_size]
y = enc_sample[1:context_size+1]
print(f"x: {x}")
print(f"y:      {y}")

x: [13, 1002, 345, 1549]
y:      [1002, 345, 1549, 588]


In [41]:
for i in range(1, context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]
    print(context, "---->", desired)

[13] ----> 1002
[13, 1002] ----> 345
[13, 1002, 345] ----> 1549
[13, 1002, 345, 1549] ----> 588


In [42]:
for i in range(1, context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]
    print(tokenizer.decode(context), "---->", tokenizer.decode([desired]))

. ---->  If
. If ---->  you
. If you ----> 'd
. If you'd ---->  like


In [43]:
import torch
from torch.utils.data import Dataset, DataLoader


class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        token_ids = tokenizer.encode(txt)    #1

        for i in range(0, len(token_ids) - max_length, stride):     #2
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):    #3
        return len(self.input_ids)

    def __getitem__(self, idx):         #4
        return self.input_ids[idx], self.target_ids[idx]

In [53]:
import torch
from torch.utils.data import Dataset, DataLoader

# The author's approach stores repeated values massivelly. 
class GPTDatasetLightStorev1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.ids = []

        token_ids = tokenizer.encode(txt)    #1

        for i in range(0, len(token_ids) - max_length, stride):     #2
            chunk = token_ids[i:i + max_length + 1]
            self.ids.append(torch.tensor(chunk))

    def __len__(self):    #3
        return len(self.ids)

    def __getitem__(self, idx):         #4
        return self.ids[idx][:-1], self.ids[idx][1:]

In [54]:
def create_dataloader_v1(txt, batch_size=4, max_length=256, stride=128, shuffle=True, drop_last=True, num_workers=0):
    tokenizer = tiktoken.get_encoding("gpt2")                         #1
    #dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)   #2
    dataset = GPTDatasetLightStorev1(txt, tokenizer, max_length, stride)   #2
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,     #3
        num_workers=num_workers     #4
    )

    return dataloader

In [55]:
dataloader = create_dataloader_v1(raw_text, batch_size=1, max_length=4, stride=1, shuffle=False)
data_iter = iter(dataloader)      #1
first_batch = next(data_iter)
print(first_batch)

[tensor([[  464, 30535,   605, 34200]]), tensor([[30535,   605, 34200,   286]])]


In [56]:
second_batch = next(data_iter)
print(second_batch)

[tensor([[30535,   605, 34200,   286]]), tensor([[  605, 34200,   286, 12068]])]


In [61]:
dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=4, stride=4,
    shuffle=False
)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

Inputs:
 tensor([[  464, 30535,   605, 34200],
        [  286, 12068, 26099,   357],
        [ 1558,  1959,     8,   628],
        [  198,   197,   197,   197],
        [  197,   197, 39443,   330],
        [17321,   628,   628,   198],
        [  198,  1558,  1959,   628],
        [  628,   198,   198,  3109]])

Targets:
 tensor([[30535,   605, 34200,   286],
        [12068, 26099,   357,  1558],
        [ 1959,     8,   628,   198],
        [  197,   197,   197,   197],
        [  197, 39443,   330, 17321],
        [  628,   628,   198,   198],
        [ 1558,  1959,   628,   628],
        [  198,   198,  3109,  9213]])


In [62]:
input_ids = torch.tensor([2, 3, 5, 1])
vocab_size = 6
output_dim = 3
torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [72]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [77]:
sum(torch.tensor([3])*embedding_layer.weight)

tensor([-5.6097,  5.1283, -6.6531], grad_fn=<AddBackward0>)

In [65]:
input_ids.shape

torch.Size([4])

In [64]:
print(embedding_layer(input_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


In [78]:
vocab_size = 50257
output_dim = 1024
token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [80]:
max_length = 8
batch_size = 16
dataloader = create_dataloader_v1(
    raw_text, batch_size=batch_size, max_length=max_length,
   stride=max_length, shuffle=False
)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Token IDs:\n", inputs)
print("\nInputs shape:\n", inputs.shape)

Token IDs:
 tensor([[  464, 30535,   605, 34200,   286, 12068, 26099,   357],
        [ 1558,  1959,     8,   628,   198,   197,   197,   197],
        [  197,   197, 39443,   330, 17321,   628,   628,   198],
        [  198,  1558,  1959,   628,   628,   198,   198,  3109],
        [ 9213,   422, 11145,   271,  1668,   319,  2805,   513],
        [   11, 32190,   628,   628,   198,   198,  1212,   670],
        [  318, 17503,    13,  1002,   345,  1549,   588,   284],
        [ 1037,  4292,   340,    11,   766,   262,  1037,  5468],
        [  290,   262,  3918,  5698,    11,   393,  2666,   257],
        [ 2912,   319,   262,  1561,  2443,    13,   628,   198],
        [  198, 10970,   198,   198,    44, 12599,  3620,  1404],
        [20151,   198,   198,    47,   371,   314,   399,   327],
        [  314,   350,   406,   412,   311,   198,   198, 19238],
        [  198,   198, 35364, 26099,    13,   628,   628,   198],
        [  198,     9,  1635,  1635,   628,   198,   198,  3886]

In [81]:
token_embeddings = token_embedding_layer(inputs)
print(token_embeddings.shape)

torch.Size([16, 8, 1024])


In [82]:
context_length = max_length
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)
pos_embeddings = pos_embedding_layer(torch.arange(context_length))
print(pos_embeddings.shape)

torch.Size([8, 1024])


In [83]:
input_embeddings = token_embeddings + pos_embeddings
print(input_embeddings.shape)

torch.Size([16, 8, 1024])


In [86]:
token_embeddings.shape, pos_embeddings.shape

(torch.Size([16, 8, 1024]), torch.Size([8, 1024]))

In [85]:
token_embeddings

tensor([[[ 8.2776e-01,  1.7748e+00,  1.0542e+00,  ...,  1.1336e+00,
          -7.7212e-01, -9.9534e-01],
         [-3.0045e+00,  1.2972e+00,  5.7636e-01,  ..., -7.0133e-01,
           2.8031e-01, -1.0529e-04],
         [ 9.7853e-01, -7.5373e-01,  2.0931e+00,  ..., -3.1714e-01,
          -1.1022e+00,  1.3077e+00],
         ...,
         [-8.4415e-01,  2.0000e+00,  6.8594e-01,  ...,  2.1394e+00,
           8.9069e-02,  4.2503e-01],
         [-4.3007e-01,  1.4692e+00, -1.3435e+00,  ..., -4.4656e-03,
          -7.2063e-01,  5.4790e-02],
         [ 2.5309e+00, -4.2481e-01, -1.1157e-03,  ...,  1.6933e+00,
          -1.6742e-01, -3.6619e-01]],

        [[ 5.8507e-01, -3.2071e-01, -2.2728e-01,  ...,  1.5466e+00,
          -9.1473e-01, -1.2528e-01],
         [ 7.9293e-01,  1.5560e-01,  9.3074e-02,  ...,  5.7123e-01,
           6.6955e-01, -8.0380e-01],
         [ 3.0769e-02, -4.3874e-01, -1.0033e+00,  ...,  1.3091e+00,
           8.8275e-02, -2.1600e+00],
         ...,
         [-7.5418e-01, -1